apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: arc-ansible-devspace
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: ansible-devspaces
spec:
  started: true
  routingClass: che
  template:
    projects:
      - name: ansible-devspaces
        git:
          remotes:
            origin: https://github.com/KhalilGibrotha/ansible-devspaces
          checkoutFrom:
            revision: develop
    components:
      - name: ansible-tools
        container:
          image: ghcr.io/ansible/ansible-devspaces@sha256:d214eed0285eb589cb1dd2cf7fe5645d73bb9862bcf3b51c0c2101f9558b1de6
          mountSources: true
          memoryLimit: 2Gi
        env:
          - name: ANSIBLE_CONFIG
            value: /projects/ansible-devspaces/ansible.cfg
          - name: DOMAIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: domain-credentials
                key: username
          - name: DOMAIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: domain-credentials
                key: password
    commands:
      - id: install-galaxy-deps
        exec:
          component: ansible-tools
          commandLine: ansible-galaxy install -r requirements.yml --force
        workingDir: /projects/ansible-devspaces
      - id: sync-upstream-repos
        exec:
          component: ansible-tools
          commandLine: bash ./scripts/clone-repos.sh
        workingDir: /projects/ansible-devspaces
      - id: bootstrap-workspace
        exec:
          component: ansible-tools
          commandLine: bash ./scripts/devspace-bootstrap.sh
        workingDir: /projects/ansible-devspaces
      - id: run-sample-playbook
        exec:
          component: ansible-tools
          commandLine: ansible-playbook playbooks/site.yml
        workingDir: /projects/ansible-devspaces
      - id: run-ansible-lint
        exec:
          component: ansible-tools
          commandLine: make lint
        workingDir: /projects/ansible-devspaces
      - id: run-test-suite
        exec:
          component: ansible-tools
          commandLine: make test
        workingDir: /projects/ansible-devspaces
