apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: arc-ansible-devspace
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: ansible-devspaces
spec:
  started: true
  routingClass: che
  template:
    projects:
      - name: ansible-devspaces-demo
        git:
          remotes:
            origin: https://github.com/KhalilGibrotha/ansible-devspaces
          checkoutFrom:
            revision: develop
    components:
      - name: ansible-tools
        container:
          image: quay.io/ansible/toolset:latest
          mountSources: true
          memoryLimit: 2Gi
          env:
            - name: ANSIBLE_CONFIG
              value: /projects/ansible-devspaces-demo/ansible.cfg
            - name: DOMAIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: domain-credentials
                  key: username
            - name: DOMAIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: domain-credentials
                  key: password
    commands:
      - id: install-galaxy-deps
        exec:
          component: ansible-tools
          commandLine: ansible-galaxy install -r requirements.yml --force
          workingDir: /projects/ansible-devspaces-demo
      - id: sync-upstream-repos
        exec:
          component: ansible-tools
          commandLine: ./scripts/clone-repos.sh
          workingDir: /projects/ansible-devspaces-demo
      - id: run-sample-playbook
        exec:
          component: ansible-tools
          commandLine: ansible-playbook playbooks/site.yml
          workingDir: /projects/ansible-devspaces-demo
      - id: run-ansible-lint
        exec:
          component: ansible-tools
          commandLine: make lint
          workingDir: /projects/ansible-devspaces-demo
      - id: run-test-suite
        exec:
          component: ansible-tools
          commandLine: make test
          workingDir: /projects/ansible-devspaces-demo
    events:
      postStart:
        - sync-upstream-repos
        - install-galaxy-deps
